/**************************************************************************\
 * Copyright (c) Kongsberg Oil & Gas Technologies AS
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the conditions in COPYING are
 * met.
\**************************************************************************/

#include "CadShaderSources.h"

namespace Obol {
namespace internal {

// GLSL shader sources – Tier 1 (GL 2.0 / GLSL 1.10, no #version directive)
// ---------------------------------------------------------------------------

// Wire pass: no lighting, colour from uniform
const char * const kWireVS1 =
    "attribute vec3 a_pos;\n"
    "uniform mat4 u_model;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform vec4 u_color;\n"
    "varying vec4 v_color;\n"
    "void main() {\n"
    "    vec4 wp = u_model * vec4(a_pos, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_color = u_color;\n"
    "}\n";

const char * const kWirePopVS1 =
    "attribute vec3 a_pos;\n"
    "uniform mat4 u_model;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform vec4 u_color;\n"
    "uniform vec3 u_popEncodeScale;\n"
    "uniform vec3 u_popDecodeScale;\n"
    "uniform vec3 u_popMin;\n"
    "varying vec4 v_color;\n"
    "void main() {\n"
    "    vec3 mask = max(u_popDecodeScale, vec3(1.0));\n"
    "    vec3 code = clamp(floor((a_pos - u_popMin) * u_popEncodeScale),\n"
    "                      vec3(0.0), vec3(65535.0));\n"
    "    vec3 snapped = min(vec3(65535.0),\n"
    "        (floor(code / mask) + vec3(0.5)) * mask);\n"
    "    vec3 p = a_pos;\n"
    "    if (u_popEncodeScale.x > 0.0) p.x = snapped.x / u_popEncodeScale.x + u_popMin.x;\n"
    "    if (u_popEncodeScale.y > 0.0) p.y = snapped.y / u_popEncodeScale.y + u_popMin.y;\n"
    "    if (u_popEncodeScale.z > 0.0) p.z = snapped.z / u_popEncodeScale.z + u_popMin.z;\n"
    "    vec4 wp = u_model * vec4(p, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_color = u_color;\n"
    "}\n";

const char * const kWireFS1 =
    "uniform int u_backgroundMask;\n"
    "uniform vec3 u_backgroundBottom;\n"
    "uniform vec3 u_backgroundTop;\n"
    "uniform vec2 u_backgroundViewport;\n"
    "varying vec4 v_color;\n"
    "void main() {\n"
    "    if (u_backgroundMask != 0) {\n"
    "        float height = max(u_backgroundViewport.y, 1.0);\n"
    "        float t = clamp((gl_FragCoord.y - u_backgroundViewport.x) / height, 0.0, 1.0);\n"
    "        gl_FragColor = vec4(mix(u_backgroundBottom, u_backgroundTop, t), 1.0);\n"
    "    } else {\n"
    "        gl_FragColor = v_color;\n"
    "    }\n"
    "}\n";

// View-local proxy points carry their own per-occurrence colour so thousands
// of differently coloured aggregate replacements remain one draw call.
const char * const kProxyPointVS1 =
    "attribute vec3 a_pos;\n"
    "attribute vec4 a_color;\n"
    "uniform mat4 u_viewProj;\n"
    "varying vec4 v_color;\n"
    "void main() {\n"
    "    gl_Position = u_viewProj * vec4(a_pos, 1.0);\n"
    "    v_color = a_color;\n"
    "}\n";

// Solid aggregate proxies use explicit box-face normals and per-proxy colour.
// A distinct colour attribute avoids aliasing the normal stream at location 1.
const char * const kProxyShadedVS1 =
    "attribute vec3 a_pos;\n"
    "attribute vec3 a_norm;\n"
    "attribute vec4 a_proxyColor;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform mat4 u_rootModel;\n"
    "uniform mat3 u_rootNormalMatrix;\n"
    "uniform int u_hasNorm;\n"
    "varying vec3 v_norm;\n"
    "varying vec3 v_worldPos;\n"
    "varying vec3 v_sourceWorldPos;\n"
    "varying vec4 v_color;\n"
    "void main() {\n"
    "    vec4 wp = vec4(a_pos, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = v_worldPos;\n"
    "    v_norm = u_rootNormalMatrix * a_norm;\n"
    "    v_color = a_proxyColor;\n"
    "}\n";

// Shaded pass: multi-light (directional/point/spot) in world space
const char * const kShadedVS1 =
    "attribute vec3 a_pos;\n"
    "attribute vec3 a_norm;\n"
    "uniform mat4  u_model;\n"
    "uniform mat3  u_normalMatrix;\n"
    "uniform mat4  u_rootModel;\n"
    "uniform mat3  u_rootNormalMatrix;\n"
    "uniform mat4  u_viewProj;\n"
    "uniform vec4  u_color;\n"
    "uniform int   u_hasNorm;\n"
    "varying vec3  v_norm;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec4 wp = u_model * vec4(a_pos, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = v_worldPos;\n"
    "    v_norm = u_rootNormalMatrix * u_normalMatrix * a_norm;\n"
    "    v_color = u_color;\n"
    "}\n";

const char * const kShadedPopVS1 =
    "attribute vec3 a_pos;\n"
    "attribute vec3 a_norm;\n"
    "uniform mat4  u_model;\n"
    "uniform mat3  u_normalMatrix;\n"
    "uniform mat4  u_rootModel;\n"
    "uniform mat3  u_rootNormalMatrix;\n"
    "uniform mat4  u_viewProj;\n"
    "uniform vec4  u_color;\n"
    "uniform int   u_hasNorm;\n"
    "uniform vec3  u_popEncodeScale;\n"
    "uniform vec3  u_popDecodeScale;\n"
    "uniform vec3  u_popMin;\n"
    "varying vec3  v_norm;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec3 mask = max(u_popDecodeScale, vec3(1.0));\n"
    "    vec3 code = clamp(floor((a_pos - u_popMin) * u_popEncodeScale),\n"
    "                      vec3(0.0), vec3(65535.0));\n"
    "    vec3 snapped = min(vec3(65535.0),\n"
    "        (floor(code / mask) + vec3(0.5)) * mask);\n"
    "    vec3 p = a_pos;\n"
    "    if (u_popEncodeScale.x > 0.0) p.x = snapped.x / u_popEncodeScale.x + u_popMin.x;\n"
    "    if (u_popEncodeScale.y > 0.0) p.y = snapped.y / u_popEncodeScale.y + u_popMin.y;\n"
    "    if (u_popEncodeScale.z > 0.0) p.z = snapped.z / u_popEncodeScale.z + u_popMin.z;\n"
    "    vec4 sourceWp = u_model * vec4(a_pos, 1.0);\n"
    "    vec4 wp = u_model * vec4(p, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = (u_rootModel * sourceWp).xyz;\n"
    "    v_norm = u_rootNormalMatrix * u_normalMatrix * a_norm;\n"
    "    v_color = u_color;\n"
    "}\n";

/* Face-normal shading derives its normal from world-position derivatives in
 * the fragment stage.  Do not make every vertex transform an a_norm value
 * that this program can never consume. */
const char * const kShadedFaceVS1 =
    "attribute vec3 a_pos;\n"
    "uniform mat4  u_model;\n"
    "uniform mat4  u_viewProj;\n"
    "uniform vec4  u_color;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec4 wp = u_model * vec4(a_pos, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = wp.xyz;\n"
    "    v_sourceWorldPos = wp.xyz;\n"
    "    v_color = u_color;\n"
    "}\n";

const char * const kShadedPopFaceVS1 =
    "attribute vec3 a_pos;\n"
    "uniform mat4  u_model;\n"
    "uniform mat4  u_viewProj;\n"
    "uniform vec4  u_color;\n"
    "uniform vec3  u_popEncodeScale;\n"
    "uniform vec3  u_popDecodeScale;\n"
    "uniform vec3  u_popMin;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec3 mask = max(u_popDecodeScale, vec3(1.0));\n"
    "    vec3 code = clamp(floor((a_pos - u_popMin) * u_popEncodeScale),\n"
    "                      vec3(0.0), vec3(65535.0));\n"
    "    vec3 snapped = min(vec3(65535.0),\n"
    "        (floor(code / mask) + vec3(0.5)) * mask);\n"
    "    vec3 p = a_pos;\n"
    "    if (u_popEncodeScale.x > 0.0) p.x = snapped.x / u_popEncodeScale.x + u_popMin.x;\n"
    "    if (u_popEncodeScale.y > 0.0) p.y = snapped.y / u_popEncodeScale.y + u_popMin.y;\n"
    "    if (u_popEncodeScale.z > 0.0) p.z = snapped.z / u_popEncodeScale.z + u_popMin.z;\n"
    "    vec4 sourceWp = u_model * vec4(a_pos, 1.0);\n"
    "    vec4 wp = u_model * vec4(p, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = wp.xyz;\n"
    "    v_sourceWorldPos = sourceWp.xyz;\n"
    "    v_color = u_color;\n"
    "}\n";

/* Keep the direct GLSL tiers visually consistent with the compatibility
 * renderer.  BRL-CAD's default material ambient remains 0.2, while
 * u_ambient supplies the active SoEnvironment RGB x intensity (0.3 for the
 * historical MGED profile and 0.18 for studio).  Diffuse is 0.6 and the
 * default zero-shininess specular term contributes 0.2 whenever a face is
 * lit. */
const char * const kShadedFS1 =
    "uniform int   u_numLights;\n"
    "uniform vec3  u_ambient;\n"
    "uniform int   u_hasNorm;\n"
    "uniform int   u_sourceFacingNormal;\n"
    "uniform int   u_ltype[8];\n"
    "uniform vec3  u_lvec[8];\n"
    "uniform vec3  u_laxis[8];\n"
    "uniform vec3  u_lcolor[8];\n"
    "uniform vec3  u_latten[8];\n"
    "uniform float u_lcos[8];\n"
    "uniform float u_lexponent[8];\n"
    "uniform vec3  u_eyeWorld;\n"
    "uniform vec3  u_viewTowardEye;\n"
    "uniform int   u_perspective;\n"
    "varying vec3  v_norm;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec3 n;\n"
    "    if (u_hasNorm != 0) {\n"
    "        n = normalize(v_norm);\n"
    "        if (u_sourceFacingNormal != 0) {\n"
    "            vec3 sourceFace = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "            if (!gl_FrontFacing) sourceFace = -sourceFace;\n"
    "            vec3 toEye = (u_perspective != 0) ?\n"
    "                normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "            if (dot(sourceFace, toEye) < 0.0) n = -n;\n"
    "        } else if (!gl_FrontFacing) n = -n;\n"
    "    } else {\n"
    "        vec3 fn = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "        if (dot(fn, fn) <= 1.0e-30)\n"
    "            fn = cross(dFdx(v_worldPos), dFdy(v_worldPos));\n"
    "        float fl = length(fn);\n"
    "        n = (fl > 0.0) ? fn / fl : vec3(0.0, 0.0, 1.0);\n"
    "        vec3 toEye = (u_perspective != 0) ?\n"
    "            normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "        if (dot(n, toEye) < 0.0) n = -n;\n"
    "    }\n"
    "    vec3 col = v_color.rgb * u_ambient * 0.2;\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        if (i >= u_numLights) break;\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (u_ltype[i] == 0) {\n"
    "            L = normalize(u_lvec[i]);\n"
    "        } else {\n"
    "            vec3 d = u_lvec[i] - v_worldPos;\n"
    "            float dl = length(d);\n"
    "            L = (dl > 0.0) ? d / dl : vec3(0.0, 0.0, 1.0);\n"
    "            float denom = dot(u_latten[i], vec3(1.0, dl, dl * dl));\n"
    "            if (denom > 0.0) atten /= denom;\n"
    "            if (u_ltype[i] == 2) {\n"
    "                float c = dot(normalize(u_laxis[i]), -L);\n"
    "                if (c < u_lcos[i]) atten = 0.0;\n"
    "                else atten *= pow(max(c, 0.0), u_lexponent[i]);\n"
    "            }\n"
    "        }\n"
    "        float ndl = max(0.0, dot(n, L));\n"
    "        float spec = (ndl > 0.0) ? 0.2 : 0.0;\n"
    "        col += v_color.rgb * u_lcolor[i] *\n"
    "               ((ndl * 0.6 + spec) * atten);\n"
    "    }\n"
    "    gl_FragColor = vec4(col, v_color.a);\n"
    "}\n";

/* The ordinary qged/mged scene has exactly one directional headlight.  Keep a
 * pair of compact shaders for that overwhelmingly common case instead of
 * making every software-rendered fragment execute the generic eight-light
 * loop, dynamically indexed uniform arrays, and both normal-generation paths.
 * The generic shader remains authoritative for mixed or multiple lights. */
const char * const kShadedDirectionalNormFS1 =
    "uniform vec3  u_lightVec;\n"
    "uniform vec3  u_lightColor;\n"
    "uniform vec3  u_ambient;\n"
    "uniform vec3  u_eyeWorld;\n"
    "uniform vec3  u_viewTowardEye;\n"
    "uniform int   u_perspective;\n"
    "uniform int   u_sourceFacingNormal;\n"
    "varying vec3  v_norm;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec3 n = normalize(v_norm);\n"
    "    if (u_sourceFacingNormal != 0) {\n"
    "        vec3 sourceFace = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "        if (!gl_FrontFacing) sourceFace = -sourceFace;\n"
    "        vec3 toEye = (u_perspective != 0) ?\n"
    "            normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "        if (dot(sourceFace, toEye) < 0.0) n = -n;\n"
    "    } else {\n"
    "        n *= gl_FrontFacing ? 1.0 : -1.0;\n"
    "    }\n"
    "    float ndl = max(0.0, dot(n, u_lightVec));\n"
    "    float spec = (ndl > 0.0) ? 0.2 : 0.0;\n"
    "    vec3 col = v_color.rgb *\n"
    "        (u_ambient * 0.2 + u_lightColor * (ndl * 0.6 + spec));\n"
    "    gl_FragColor = vec4(col, v_color.a);\n"
    "}\n";

const char * const kShadedDirectionalFaceFS1 =
    "uniform vec3  u_lightVec;\n"
    "uniform vec3  u_lightColor;\n"
    "uniform vec3  u_ambient;\n"
    "uniform vec3  u_eyeWorld;\n"
    "uniform vec3  u_viewTowardEye;\n"
    "uniform int   u_perspective;\n"
    "varying vec3  v_worldPos;\n"
    "varying vec3  v_sourceWorldPos;\n"
    "varying vec4  v_color;\n"
    "void main() {\n"
    "    vec3 fn = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "    if (dot(fn, fn) <= 1.0e-30)\n"
    "        fn = cross(dFdx(v_worldPos), dFdy(v_worldPos));\n"
    "    float fl = length(fn);\n"
    "    vec3 n = (fl > 0.0) ? fn / fl : vec3(0.0, 0.0, 1.0);\n"
    "    vec3 toEye = (u_perspective != 0) ?\n"
    "        normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "    n *= 2.0 * step(0.0, dot(n, toEye)) - 1.0;\n"
    "    float ndl = max(0.0, dot(n, u_lightVec));\n"
    "    float spec = (ndl > 0.0) ? 0.2 : 0.0;\n"
    "    vec3 col = v_color.rgb *\n"
    "        (u_ambient * 0.2 + u_lightColor * (ndl * 0.6 + spec));\n"
    "    gl_FragColor = vec4(col, v_color.a);\n"
    "}\n";

const char * const kShadedFaceDebugFS1 =
    "void main() {\n"
    "    gl_FragColor = gl_FrontFacing ?\n"
    "        vec4(1.0, 0.0, 0.0, 1.0) : vec4(0.0, 0.0, 1.0, 1.0);\n"
    "}\n";

const char * const kShadedNormalDebugFS1 =
    "uniform int u_hasNorm;\n"
    "varying vec3 v_norm;\n"
    "void main() {\n"
    "    vec3 n = normalize(v_norm);\n"
    "    if (!gl_FrontFacing) n = -n;\n"
    "    gl_FragColor = (u_hasNorm == 0) ?\n"
    "        vec4(1.0, 1.0, 0.0, 1.0) :\n"
    "        vec4(n * 0.5 + vec3(0.5), 1.0);\n"
    "}\n";

// ---------------------------------------------------------------------------
// GLSL shader sources – Tier 2 (GL 3.1+ / GLSL 1.40, instanced)
// Per-instance transform and color are passed as vertex attributes with
// divisor=1.  The mat4 occupies 4 consecutive attribute locations.
// ---------------------------------------------------------------------------

const char * const kWireVS2 =
    "#version 140\n"
    "in vec3  a_pos;\n"
    "in mat4  a_instTransform;\n"  // locations: BASE_INST_LOC .. BASE_INST_LOC+3
    "in vec4  a_instColor;\n"      // location:  BASE_INST_LOC+4
    "uniform mat4 u_viewProj;\n"
    "uniform vec4 u_geometryColor;\n"
    "uniform int u_useGeometryColor;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    gl_Position = u_viewProj * a_instTransform * vec4(a_pos, 1.0);\n"
    "    v_color = (u_useGeometryColor != 0) ?\n"
    "        vec4(u_geometryColor.rgb, u_geometryColor.a * a_instColor.a) : a_instColor;\n"
    "}\n";

const char * const kWirePopVS2 =
    "#version 140\n"
    "in vec3  a_pos;\n"
    "in mat4  a_instTransform;\n"
    "in vec4  a_instColor;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform vec4 u_geometryColor;\n"
    "uniform int u_useGeometryColor;\n"
    "uniform vec3 u_popEncodeScale;\n"
    "uniform vec3 u_popDecodeScale;\n"
    "uniform vec3 u_popMin;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec3 mask = max(u_popDecodeScale, vec3(1.0));\n"
    "    vec3 code = clamp(floor((a_pos - u_popMin) * u_popEncodeScale),\n"
    "                      vec3(0.0), vec3(65535.0));\n"
    "    vec3 snapped = min(vec3(65535.0),\n"
    "        (floor(code / mask) + vec3(0.5)) * mask);\n"
    "    vec3 p = a_pos;\n"
    "    if (u_popEncodeScale.x > 0.0) p.x = snapped.x / u_popEncodeScale.x + u_popMin.x;\n"
    "    if (u_popEncodeScale.y > 0.0) p.y = snapped.y / u_popEncodeScale.y + u_popMin.y;\n"
    "    if (u_popEncodeScale.z > 0.0) p.z = snapped.z / u_popEncodeScale.z + u_popMin.z;\n"
    "    gl_Position = u_viewProj * a_instTransform * vec4(p, 1.0);\n"
    "    v_color = (u_useGeometryColor != 0) ?\n"
    "        vec4(u_geometryColor.rgb, u_geometryColor.a * a_instColor.a) : a_instColor;\n"
    "}\n";

const char * const kWireFS2 =
    "#version 140\n"
    "in  vec4 v_color;\n"
    "out vec4 fragColor;\n"
    "void main() { fragColor = v_color; }\n";

const char * const kShadedVS2 =
    "#version 140\n"
    "in vec3  a_pos;\n"
    "in vec3  a_norm;\n"
    "in mat4  a_instTransform;\n"
    "in mat3  a_instNormalTransform;\n"
    "in vec4  a_instColor;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform mat4 u_rootModel;\n"
    "uniform mat3 u_rootNormalMatrix;\n"
    "uniform int  u_hasNorm;\n"
    "out vec3 v_norm;\n"
    "out vec3 v_worldPos;\n"
    "out vec3 v_sourceWorldPos;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec4 wp = a_instTransform * vec4(a_pos, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = v_worldPos;\n"
    "    if (u_hasNorm != 0) {\n"
    "        v_norm = u_rootNormalMatrix * a_instNormalTransform * a_norm;\n"
    "    } else {\n"
    "        v_norm = vec3(0.0, 0.0, 1.0);\n"
    "    }\n"
    "    v_color = a_instColor;\n"
    "}\n";

const char * const kShadedPopVS2 =
    "#version 140\n"
    "in vec3  a_pos;\n"
    "in vec3  a_norm;\n"
    "in mat4  a_instTransform;\n"
    "in mat3  a_instNormalTransform;\n"
    "in vec4  a_instColor;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform mat4 u_rootModel;\n"
    "uniform mat3 u_rootNormalMatrix;\n"
    "uniform int  u_hasNorm;\n"
    "uniform vec3 u_popEncodeScale;\n"
    "uniform vec3 u_popDecodeScale;\n"
    "uniform vec3 u_popMin;\n"
    "out vec3 v_norm;\n"
    "out vec3 v_worldPos;\n"
    "out vec3 v_sourceWorldPos;\n"
    "out vec4 v_color;\n"
    "void main() {\n"
    "    vec3 mask = max(u_popDecodeScale, vec3(1.0));\n"
    "    vec3 code = clamp(floor((a_pos - u_popMin) * u_popEncodeScale),\n"
    "                      vec3(0.0), vec3(65535.0));\n"
    "    vec3 snapped = min(vec3(65535.0),\n"
    "        (floor(code / mask) + vec3(0.5)) * mask);\n"
    "    vec3 p = a_pos;\n"
    "    if (u_popEncodeScale.x > 0.0) p.x = snapped.x / u_popEncodeScale.x + u_popMin.x;\n"
    "    if (u_popEncodeScale.y > 0.0) p.y = snapped.y / u_popEncodeScale.y + u_popMin.y;\n"
    "    if (u_popEncodeScale.z > 0.0) p.z = snapped.z / u_popEncodeScale.z + u_popMin.z;\n"
    "    vec4 sourceWp = a_instTransform * vec4(a_pos, 1.0);\n"
    "    vec4 wp = a_instTransform * vec4(p, 1.0);\n"
    "    gl_Position = u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = (u_rootModel * sourceWp).xyz;\n"
    "    if (u_hasNorm != 0) {\n"
    "        v_norm = u_rootNormalMatrix * a_instNormalTransform * a_norm;\n"
    "    } else {\n"
    "        v_norm = vec3(0.0, 0.0, 1.0);\n"
    "    }\n"
    "    v_color = a_instColor;\n"
    "}\n";

const char * const kShadedFS2 =
    "#version 140\n"
    "uniform int   u_numLights;\n"
    "uniform vec3  u_ambient;\n"
    "uniform int   u_hasNorm;\n"
    "uniform int   u_sourceFacingNormal;\n"
    "uniform int   u_ltype[8];\n"
    "uniform vec3  u_lvec[8];\n"
    "uniform vec3  u_laxis[8];\n"
    "uniform vec3  u_lcolor[8];\n"
    "uniform vec3  u_latten[8];\n"
    "uniform float u_lcos[8];\n"
    "uniform float u_lexponent[8];\n"
    "uniform vec3  u_eyeWorld;\n"
    "uniform vec3  u_viewTowardEye;\n"
    "uniform int   u_perspective;\n"
    "in  vec3 v_norm;\n"
    "in  vec3 v_worldPos;\n"
    "in  vec3 v_sourceWorldPos;\n"
    "in  vec4 v_color;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec3 n;\n"
    "    if (u_hasNorm != 0) {\n"
    "        n = normalize(v_norm);\n"
    "        if (u_sourceFacingNormal != 0) {\n"
    "            vec3 sourceFace = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "            if (!gl_FrontFacing) sourceFace = -sourceFace;\n"
    "            vec3 toEye = (u_perspective != 0) ?\n"
    "                normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "            if (dot(sourceFace, toEye) < 0.0) n = -n;\n"
    "        } else if (!gl_FrontFacing) n = -n;\n"
    "    } else {\n"
    "        vec3 fn = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "        if (dot(fn, fn) <= 1.0e-30)\n"
    "            fn = cross(dFdx(v_worldPos), dFdy(v_worldPos));\n"
    "        float fl = length(fn);\n"
    "        n = (fl > 0.0) ? fn / fl : vec3(0.0, 0.0, 1.0);\n"
    "        vec3 toEye = (u_perspective != 0) ?\n"
    "            normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "        if (dot(n, toEye) < 0.0) n = -n;\n"
    "    }\n"
    "    vec3 col = v_color.rgb * u_ambient * 0.2;\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        if (i >= u_numLights) break;\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (u_ltype[i] == 0) {\n"
    "            L = normalize(u_lvec[i]);\n"
    "        } else {\n"
    "            vec3 d = u_lvec[i] - v_worldPos;\n"
    "            float dl = length(d);\n"
    "            L = (dl > 0.0) ? d / dl : vec3(0.0, 0.0, 1.0);\n"
    "            float denom = dot(u_latten[i], vec3(1.0, dl, dl * dl));\n"
    "            if (denom > 0.0) atten /= denom;\n"
    "            if (u_ltype[i] == 2) {\n"
    "                float c = dot(normalize(u_laxis[i]), -L);\n"
    "                if (c < u_lcos[i]) atten = 0.0;\n"
    "                else atten *= pow(max(c, 0.0), u_lexponent[i]);\n"
    "            }\n"
    "        }\n"
    "        float ndl = max(0.0, dot(n, L));\n"
    "        float spec = (ndl > 0.0) ? 0.2 : 0.0;\n"
    "        col += v_color.rgb * u_lcolor[i] *\n"
    "               ((ndl * 0.6 + spec) * atten);\n"
    "    }\n"
    "    fragColor = vec4(col, v_color.a);\n"
    "}\n";

/*
 * Cross-part indirect shading.  Unlike the older per-part instanced shader,
 * every value that differs by part or PoP cut is an instance attribute.
 * baseInstance in each indirect command selects the appropriate records, so
 * thousands of unrelated mesh ranges share one program and one submission.
 */
const char * const kShadedIndirectVS2 =
    "#version 140\n"
    "in vec3  a_pos;\n"
    "in vec3  a_norm;\n"
    "in mat4  a_instTransform;\n"
    "in mat3  a_instNormalTransform;\n"
    "in vec4  a_instColor;\n"
    "in vec4  a_instPopMinLevel;\n"
    "in vec4  a_instPopMaxFlags;\n"
    "uniform mat4 u_viewProj;\n"
    "uniform mat4 u_rootModel;\n"
    "uniform mat3 u_rootNormalMatrix;\n"
    "out vec3 v_norm;\n"
    "out vec3 v_worldPos;\n"
    "out vec3 v_sourceWorldPos;\n"
    "out vec4 v_color;\n"
    "flat out float v_hasNorm;\n"
    "flat out float v_sourceFacingNormal;\n"
    "void main() {\n"
    "    float packedFlags = floor(a_instPopMaxFlags.w + 0.5);\n"
    "    float hasNorm = mod(packedFlags, 2.0);\n"
    "    bool progressive = mod(floor(packedFlags / 2.0), 2.0) > 0.5;\n"
    "    bool hidden = packedFlags >= 4.0;\n"
    "    vec3 p = a_pos;\n"
    "    float quantCode = floor(a_instPopMinLevel.w + 0.5);\n"
    "    vec3 quantBits;\n"
    "    quantBits.x = mod(quantCode, 17.0);\n"
    "    quantCode = floor(quantCode / 17.0);\n"
    "    quantBits.y = mod(quantCode, 17.0);\n"
    "    quantBits.z = floor(quantCode / 17.0);\n"
    "    bool exactQuant = all(lessThan(quantBits, vec3(0.5))) ||\n"
    "        all(greaterThanEqual(quantBits, vec3(16.0)));\n"
    "    if (progressive && !exactQuant) {\n"
    "        vec3 mask = exp2(vec3(16.0) - clamp(quantBits, 1.0, 16.0));\n"
    "        vec3 minimum = a_instPopMinLevel.xyz;\n"
    "        vec3 extent = a_instPopMaxFlags.xyz - minimum;\n"
    "        vec3 safeExtent = max(extent, vec3(1.0e-30));\n"
    "        vec3 code = clamp(floor((a_pos - minimum) *\n"
    "            (vec3(65535.0) / safeExtent)), vec3(0.0), vec3(65535.0));\n"
    "        vec3 snapped = min(vec3(65535.0),\n"
    "            (floor(code / mask) + vec3(0.5)) * mask);\n"
    "        vec3 quantized = snapped * extent / 65535.0 + minimum;\n"
    "        p = mix(a_pos, quantized, greaterThan(extent, vec3(0.0)));\n"
    "    }\n"
    "    vec4 sourceWp = a_instTransform * vec4(a_pos, 1.0);\n"
    "    vec4 wp = a_instTransform * vec4(p, 1.0);\n"
    "    gl_Position = hidden ? vec4(2.0, 2.0, 2.0, 1.0) :\n"
    "        u_viewProj * wp;\n"
    "    v_worldPos = (u_rootModel * wp).xyz;\n"
    "    v_sourceWorldPos = (u_rootModel * sourceWp).xyz;\n"
    "    if (hasNorm > 0.5) {\n"
    "        v_norm = u_rootNormalMatrix * a_instNormalTransform * a_norm;\n"
    "    } else {\n"
    "        v_norm = vec3(0.0, 0.0, 1.0);\n"
    "    }\n"
    "    v_hasNorm = hasNorm;\n"
    "    v_sourceFacingNormal = hasNorm *\n"
    "        ((progressive && !exactQuant) ? 1.0 : 0.0);\n"
    "    v_color = a_instColor;\n"
    "}\n";

const char * const kShadedIndirectFS2 =
    "#version 140\n"
    "uniform int   u_numLights;\n"
    "uniform vec3  u_ambient;\n"
    "uniform int   u_ltype[8];\n"
    "uniform vec3  u_lvec[8];\n"
    "uniform vec3  u_laxis[8];\n"
    "uniform vec3  u_lcolor[8];\n"
    "uniform vec3  u_latten[8];\n"
    "uniform float u_lcos[8];\n"
    "uniform float u_lexponent[8];\n"
    "uniform vec3  u_eyeWorld;\n"
    "uniform vec3  u_viewTowardEye;\n"
    "uniform int   u_perspective;\n"
    "in  vec3 v_norm;\n"
    "in  vec3 v_worldPos;\n"
    "in  vec3 v_sourceWorldPos;\n"
    "in  vec4 v_color;\n"
    "flat in float v_hasNorm;\n"
    "flat in float v_sourceFacingNormal;\n"
    "out vec4 fragColor;\n"
    "void main() {\n"
    "    vec3 n;\n"
    "    if (v_hasNorm > 0.5) {\n"
    "        n = normalize(v_norm);\n"
    "        if (v_sourceFacingNormal > 0.5) {\n"
    "            vec3 sourceFace = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "            if (!gl_FrontFacing) sourceFace = -sourceFace;\n"
    "            vec3 toEye = (u_perspective != 0) ?\n"
    "                normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "            if (dot(sourceFace, toEye) < 0.0) n = -n;\n"
    "        } else if (!gl_FrontFacing) n = -n;\n"
    "    } else {\n"
    "        vec3 fn = cross(dFdx(v_sourceWorldPos), dFdy(v_sourceWorldPos));\n"
    "        if (dot(fn, fn) <= 1.0e-30)\n"
    "            fn = cross(dFdx(v_worldPos), dFdy(v_worldPos));\n"
    "        float fl = length(fn);\n"
    "        n = (fl > 0.0) ? fn / fl : vec3(0.0, 0.0, 1.0);\n"
    "        vec3 toEye = (u_perspective != 0) ?\n"
    "            normalize(u_eyeWorld - v_worldPos) : u_viewTowardEye;\n"
    "        if (dot(n, toEye) < 0.0) n = -n;\n"
    "    }\n"
    "    vec3 col = v_color.rgb * u_ambient * 0.2;\n"
    "    for (int i = 0; i < 8; i++) {\n"
    "        if (i >= u_numLights) break;\n"
    "        vec3 L;\n"
    "        float atten = 1.0;\n"
    "        if (u_ltype[i] == 0) {\n"
    "            L = normalize(u_lvec[i]);\n"
    "        } else {\n"
    "            vec3 d = u_lvec[i] - v_worldPos;\n"
    "            float dl = length(d);\n"
    "            L = (dl > 0.0) ? d / dl : vec3(0.0, 0.0, 1.0);\n"
    "            float denom = dot(u_latten[i], vec3(1.0, dl, dl * dl));\n"
    "            if (denom > 0.0) atten /= denom;\n"
    "            if (u_ltype[i] == 2) {\n"
    "                float c = dot(normalize(u_laxis[i]), -L);\n"
    "                if (c < u_lcos[i]) atten = 0.0;\n"
    "                else atten *= pow(max(c, 0.0), u_lexponent[i]);\n"
    "            }\n"
    "        }\n"
    "        float ndl = max(0.0, dot(n, L));\n"
    "        float spec = (ndl > 0.0) ? 0.2 : 0.0;\n"
    "        col += v_color.rgb * u_lcolor[i] *\n"
    "               ((ndl * 0.6 + spec) * atten);\n"
    "    }\n"
    "    fragColor = vec4(col, v_color.a);\n"
    "}\n";


} // namespace internal
} // namespace Obol
