/**************************************************************************\
 * Copyright (c) Kongsberg Oil & Gas Technologies AS
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 *
 * Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
\**************************************************************************/

/**
 * @file obol_render.cpp
 * @brief Rendering test runner for the Obol library.
 *
 * Produces reference images for all registered visual tests.  Each test
 * either writes a single control image (simple scenes) or a sequence of
 * images (interaction tests that demonstrate feature behaviour over
 * multiple states).
 *
 * Every test registered here also runs in the interactive obol_viewer;
 * the shared scene factories in testlib/test_scenes.h guarantee that both
 * executables render identical scenes.
 *
 * Usage:
 *   obol_render                           List all render tests
 *   obol_render list                      List all render tests
 *   obol_render list --categories         List tests grouped by category
 *   obol_render run <name> <outpath>      Render test scene to file(s)
 *   obol_render run <name> <outpath> W H  Render with explicit resolution
 *   obol_render run_all <outdir>          Render every test to <outdir>/
 *   obol_render render_test <name> [base] Run legacy render test by name
 *   obol_render help                      Show this help
 *
 * Output files:
 *   Single-image tests:  <outpath>.rgb
 *   Sequence tests:      <outpath>_0.rgb, <outpath>_1.rgb, …
 *
 * Exit codes: 0 = all passed, non-zero = failures or error.
 */

#include "testlib/test_registry.h"
#include "utils/headless_utils.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#include <algorithm>

// Forward-declared in render_test_dispatch.cpp (generated by CMake).
int dispatchRenderTest(const std::string& name, const std::string& basepath);

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

static void printHelp(const char* argv0)
{
    printf(
        "Usage:\n"
        "  %1$s                              List all render tests\n"
        "  %1$s list                         List all render tests\n"
        "  %1$s list --categories            List render tests grouped by category\n"
        "  %1$s run <name> <outpath> [W H]   Render test scene to <outpath>.rgb\n"
        "                                     (sequence tests write _0.rgb, _1.rgb, ...)\n"
        "  %1$s run_all <outdir>             Render all tests into <outdir>/\n"
        "  %1$s render_test <name> [base]    Run legacy render test (writes <base>.rgb)\n"
        "  %1$s help                         Show this help\n"
        "\n"
        "Exit codes: 0 = all passed, non-zero = failures or error.\n"
        "\n"
        "Note: non-graphical unit tests are not run by this executable.\n"
        "      Use obol_unittest for unit tests.\n",
        argv0);
}

static const char* testFlags(bool hasSeq, bool hasInteract)
{
    if (hasSeq && hasInteract) return "seq+interact";
    if (hasSeq)                return "sequence";
    if (hasInteract)           return "interactive";
    return "static";
}

static void cmdList(bool byCategory)
{
    ObolTest::TestRegistry& reg = ObolTest::TestRegistry::instance();

    if (byCategory) {
        std::vector<std::string> cats = reg.getCategories();
        for (const auto& cat : cats) {
            ObolTest::TestCategory tc = ObolTest::categoryFromString(cat);
            auto tests = reg.getByCategory(tc);
            bool hasVisual = false;
            for (const auto* e : tests) {
                if (e->has_visual) { hasVisual = true; break; }
            }
            if (!hasVisual) continue;
            printf("[%s]\n", cat.c_str());
            for (const auto* e : tests) {
                if (!e->has_visual) continue;
                const char* flags = testFlags(!!e->render_sequence, e->has_interactive);
                /* Prefix flags with space for inline display */
                char flagbuf[32];
                if (flags[0]) snprintf(flagbuf, sizeof(flagbuf), " [%s]", flags);
                else flagbuf[0] = '\0';
                printf("  %-35s  %s%s\n",
                       e->name.c_str(), e->description.c_str(), flagbuf);
            }
            printf("\n");
        }
    } else {
        const auto& tests = reg.allTests();
        printf("%-35s  %-16s  %-12s  %s\n",
               "Name", "Category", "Flags", "Description");
        printf("%-35s  %-16s  %-12s  %s\n",
               "-----------------------------------",
               "----------------",
               "------------",
               "-----------------------------------");
        int count = 0;
        for (const auto& e : tests) {
            if (!e.has_visual) continue;
            printf("%-35s  %-16s  %-12s  %s\n",
                   e.name.c_str(),
                   ObolTest::categoryToString(e.category).c_str(),
                   testFlags(!!e.render_sequence, e.has_interactive),
                   e.description.c_str());
            ++count;
        }
        printf("\nTotal: %d render test(s)\n", count);
    }
}

static int cmdRun(const std::string& name, const std::string& outpath,
                  int width, int height)
{
    ObolTest::TestRegistry& reg = ObolTest::TestRegistry::instance();
    const ObolTest::TestEntry* entry = reg.findTest(name);

    if (!entry) {
        fprintf(stderr, "obol_render: unknown test '%s'\n", name.c_str());
        return 1;
    }
    if (!entry->has_visual) {
        fprintf(stderr, "obol_render: test '%s' has no visual output "
                "(use obol_unittest instead)\n", name.c_str());
        return 1;
    }

    // Sequence path: test provides its own multi-frame render function
    if (entry->render_sequence) {
        int rc = entry->render_sequence(outpath, width, height);
        if (rc != 0) {
            fprintf(stderr, "obol_render: '%s' sequence render failed\n",
                    name.c_str());
        }
        return rc;
    }

    // Single-image path: use the scene factory
    bool ok = reg.renderTestToFile(name, outpath, width, height);
    if (!ok) {
        fprintf(stderr, "obol_render: '%s' render failed\n", name.c_str());
        return 1;
    }
    return 0;
}

static int cmdRunAll(const std::string& outdir, int width, int height)
{
    ObolTest::TestRegistry& reg = ObolTest::TestRegistry::instance();
    const auto& tests = reg.allTests();
    int failures = 0;
    int count = 0;
    for (const auto& e : tests) {
        if (!e.has_visual) continue;
        std::string outpath = outdir + "/" + e.name;
        printf("[RENDER] %s\n", e.name.c_str());
        fflush(stdout);
        int rc;
        if (e.render_sequence) {
            rc = e.render_sequence(outpath, width, height);
        } else {
            rc = reg.renderTestToFile(e.name, outpath, width, height) ? 0 : 1;
        }
        printf("[%s] %s\n", (rc == 0 ? "PASS" : "FAIL"), e.name.c_str());
        if (rc != 0) ++failures;
        ++count;
    }
    printf("\nRendered %d test(s); %d failure(s).\n", count, failures);
    return failures;
}

// -------------------------------------------------------------------------
// main
// -------------------------------------------------------------------------
int main(int argc, char** argv)
{
    // Initialise Coin with GL context (OSMesa or GLX depending on build)
    initCoinHeadless();

    if (argc < 2 || strcmp(argv[1], "list") == 0) {
        bool byCat = (argc >= 3 && strcmp(argv[2], "--categories") == 0);
        cmdList(byCat);
        return 0;
    }

    if (strcmp(argv[1], "help") == 0 || strcmp(argv[1], "--help") == 0) {
        printHelp(argv[0]);
        return 0;
    }

    const std::string cmd = argv[1];

    // ---- run ------------------------------------------------------------
    if (cmd == "run") {
        if (argc < 4) {
            fprintf(stderr, "Usage: %s run <name> <outpath> [width height]\n",
                    argv[0]);
            return 1;
        }
        int w = (argc >= 6) ? atoi(argv[4]) : 800;
        int h = (argc >= 6) ? atoi(argv[5]) : 600;
        if (w <= 0) w = 800;
        if (h <= 0) h = 600;
        return cmdRun(argv[2], argv[3], w, h);
    }

    // ---- run_all --------------------------------------------------------
    if (cmd == "run_all") {
        if (argc < 3) {
            fprintf(stderr, "Usage: %s run_all <outdir> [width height]\n",
                    argv[0]);
            return 1;
        }
        int w = (argc >= 5) ? atoi(argv[3]) : 800;
        int h = (argc >= 5) ? atoi(argv[4]) : 600;
        if (w <= 0) w = 800;
        if (h <= 0) h = 600;
        return cmdRunAll(argv[2], w, h);
    }

    // ---- render_test (legacy dispatch) ----------------------------------
    if (cmd == "render_test") {
        if (argc < 3) {
            fprintf(stderr, "Usage: %s render_test <name> [basepath]\n",
                    argv[0]);
            return 1;
        }
        const std::string basepath = (argc >= 4) ? argv[3] : "";
        int rc = dispatchRenderTest(argv[2], basepath);
        if (rc == -1) {
            fprintf(stderr, "Unknown render test: '%s'\n", argv[2]);
            return 1;
        }
        if (rc == -2) {
            fprintf(stderr, "render_test: basepath too long (max 4095 chars)\n");
            return 1;
        }
        return rc;
    }

    fprintf(stderr, "Unknown command '%s'. Run '%s help' for usage.\n",
            argv[1], argv[0]);
    return 1;
}
