/*
 * render_stt_gl.cpp -- OpenGL version of the stt_reference scene
 *
 * Renders the same five text rows as stt_reference.cpp using SoText2 nodes
 * in a 400×200 OSMesa viewport.  The world coordinates are computed so that
 * each string's first glyph top lands on exactly the same image row as the
 * corresponding row in the stt_reference PNG, enabling a true pixel-for-pixel
 * apples-to-apples comparison.
 *
 * Coordinate derivation (see docs/stt_gl_coords.md for full derivation):
 *   - Viewport: 400×200, ortho camera height=200
 *   - world_y = VP_H/2 - y_top - font_size  (matches stt_reference y_top)
 *   - world_x = x_start - 200            (x_start=5 for all rows)
 *
 * Usage: render_stt_gl <output_base>
 * Writes <output_base>.rgb (SGI RGB, 400×200).
 *
 * The control image for comparison is generated by stt_reference:
 *   stt_reference /tmp/stt_ref.png
 */

#include "headless_utils.h"
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/nodes/SoDirectionalLight.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoTranslation.h>
#include <Inventor/nodes/SoFont.h>
#include <Inventor/nodes/SoText2.h>
#include <cstdio>
#include <cstring>

/* Matches the TextSpec rows in stt_reference.cpp */
struct RowSpec {
    float       size;
    const char *text;
    int         x_start;   /* image X of glyph left edge  */
    int         y_top;     /* image Y of glyph top pixel  */
    float       r, g, b;   /* 0..1 colour                 */
};

static const RowSpec k_rows[] = {
    { 14.0f, "Hello World",  5,   5, 1.0f,          1.0f,          1.0f          },
    { 18.0f, "Coin3D Text",  5,  35, 0.0f,          1.0f,          1.0f          },
    { 12.0f, "ABC 123",      5,  75, 1.0f,          1.0f,          0.0f          },
    { 12.0f, "Line Two",     5,  95, 1.0f,          1.0f,          0.0f          },
    { 20.0f, "3D Test",      5, 130, 51/255.0f,  204/255.0f,   76/255.0f  },
    {  0.0f, nullptr,        0,   0, 0.0f,          0.0f,          0.0f          },
};

/*
 * Viewport dimensions must match stt_reference canvas.
 */
static const int VP_W = 400;
static const int VP_H = 200;

int main(int argc, char **argv)
{
    initCoinHeadless();

    SoSeparator *root = new SoSeparator;
    root->ref();

    /*
     * Orthographic camera: height=200 world units maps 1:1 to the 200-pixel
     * viewport height.  Together with the 400-pixel width the coordinate
     * mapping is:
     *   screen_x = world_x + VP_W/2   (= world_x + 200)
     *   screen_y = world_y + VP_H/2   (= world_y + 100)
     * where screen_y=0 is the bottom of the framebuffer.
     */
    SoOrthographicCamera *cam = new SoOrthographicCamera;
    cam->position.setValue(0.0f, 0.0f, 10.0f);
    cam->height.setValue((float)VP_H);
    cam->nearDistance.setValue(1.0f);
    cam->farDistance.setValue(20.0f);
    root->addChild(cam);

    /* A minimal directional light so SoLazyElement::getDiffuse picks up the
       material colour (SoText2 uses BASE_COLOR internally, so the light does
       not actually shade the text, but Coin's traversal expects one). */
    SoDirectionalLight *light = new SoDirectionalLight;
    light->direction.setValue(0.0f, 0.0f, -1.0f);
    root->addChild(light);

    for (int ri = 0; k_rows[ri].text != nullptr; ri++) {
        const RowSpec &row = k_rows[ri];

        /*
         * Derive world anchor (= SoText2 origin = text baseline, LEFT edge).
         *
         * SoText2 places the LEFT edge of the first glyph at:
         *   screen_x = nilpoint_x  (for LEFT justification, bbmin_x=0)
         *   screen_y = nilpoint_y  (= baseline)
         *
         * For the glyph top in image coords to match stt_reference:
         *   image_y_glyph_top = y_top + size - bearing_y
         * For ProFont all chars have bearing_y == height, so the glyph top is
         *   image_y_glyph_top = y_top  (for caps/tall glyphs)
         *   image_y_glyph_top = y_top + size - bearing_y  (general)
         *
         * The SoText2 rendering places the glyph top at screen_y + bearing_y.
         * In image coords (image_y = VP_H - 1 - screen_y):
         *   image_y_glyph_top = VP_H - 1 - (nilpoint_y + bearing_y)
         *
         * For ProFont bearing_y == height == (approx) size * scale, but the
         * exact height is determined by stb/struetype rasterization.  To keep
         * this independent of exact bearing values we match the BASELINE:
         *
         *   The stt_reference baseline (bottom of caps) is at image_y = y_top + size.
         *   In screen coords: screen_y_baseline = VP_H - 1 - (y_top + size)
         *   nilpoint_y = screen_y_baseline
         *
         *   world_y = nilpoint_y - VP_H/2 = VP_H - 1 - y_top - size - VP_H/2
         *           = VP_H/2 - y_top - size   (for VP_H=200: 100 - y_top - size)
         */
        float world_x = (float)row.x_start - (float)(VP_W / 2); /* = x_start - 200 */
        float world_y = (float)(VP_H / 2)   - (float)row.y_top - row.size;

        SoSeparator *sep = new SoSeparator;

        SoTranslation *t = new SoTranslation;
        t->translation.setValue(world_x, world_y, 0.0f);
        sep->addChild(t);

        SoFont *font = new SoFont;
        font->size.setValue(row.size);
        sep->addChild(font);

        SoMaterial *mat = new SoMaterial;
        mat->diffuseColor.setValue(row.r, row.g, row.b);
        mat->emissiveColor.setValue(row.r * 0.9f, row.g * 0.9f, row.b * 0.9f);
        sep->addChild(mat);

        SoText2 *text = new SoText2;
        text->string.setValue(row.text);
        text->justification.setValue(SoText2::LEFT);
        sep->addChild(text);

        root->addChild(sep);
    }

    char outpath[1024];
    if (argc > 1)
        snprintf(outpath, sizeof(outpath), "%s.rgb", argv[1]);
    else
        snprintf(outpath, sizeof(outpath), "render_stt_gl.rgb");

    bool ok = renderToFile(root, outpath, VP_W, VP_H);
    root->unref();
    return ok ? 0 : 1;
}
